-- ============================================================
-- Abilisto — Postgres (Supabase) schema, hand-converted from
-- the MySQL/MariaDB schema (u942667021_abilisto_db).
--
-- Structure: (1) tables with columns/PK/CHECKs only, no FKs;
-- (2) the shared updated_at trigger function + per-table
-- triggers; (3) views; (4) indexes; (5) foreign keys — kept
-- last and separate (like the original dump's own "Constraints
-- for dumped tables" section) so table-creation order never
-- matters.
--
-- id columns use GENERATED BY DEFAULT AS IDENTITY (not ALWAYS)
-- so the one-off ETL script can insert explicit legacy IDs
-- without needing OVERRIDING SYSTEM VALUE; the ETL script must
-- reset each sequence to MAX(id)+1 after loading.
--
-- A few CHECK-constrained columns (users.municipality,
-- job_broadcasts.urgency, wallet_transactions.reference_type,
-- greenloop_reports.status) additionally allow '' — MySQL's ENUM
-- silently coerces an out-of-list value to '' under non-strict
-- mode, and real historical rows have this. Preserved as-is
-- rather than reinterpreted during migration.
--
-- wallet_transactions.reference_type also had its allow-list widened
-- beyond the original 3-value MySQL enum ('booking','withdrawal','fee'):
-- the app's own code (wallet_manager.php, worker/wallet.php's tab filter)
-- actually writes and reads 'topup','listo_points','listo_reward',
-- 'final_commission', and 'final_payment' too — MySQL was silently
-- blanking these to '' on every insert (a real, silent pre-existing bug),
-- which broke the wallet page's Listo Points tab filtering. Fixed going
-- forward rather than reproduced, since the data is genuinely used for
-- display logic.
-- ============================================================

-- ── 1. TABLES ────────────────────────────────────────────────

CREATE TABLE admin_expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  expense_type TEXT NOT NULL CHECK (expense_type IN ('MOOE','PS')),
  category VARCHAR(100) NOT NULL,
  description TEXT,
  amount NUMERIC(10,2) NOT NULL,
  expense_date DATE NOT NULL,
  logged_by INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);
COMMENT ON COLUMN admin_expenses.logged_by IS 'hr/admin user_id, not FK-enforced';

CREATE TABLE admin_wallet (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  balance NUMERIC(10,2) DEFAULT 0.00,
  total_earned NUMERIC(10,2) DEFAULT 0.00,
  total_earned_booking NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_earned_commission NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_withdrawn NUMERIC(10,2) DEFAULT 0.00,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON COLUMN admin_wallet.total_earned_booking IS 'Real ₱30 platform fees paid from worker wallet_balance (free credits excluded)';
COMMENT ON COLUMN admin_wallet.total_earned_commission IS '4% commission on final client payments';

CREATE TABLE bookings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  broadcast_id INTEGER,
  expires_at TIMESTAMP,
  client_id INTEGER NOT NULL,
  worker_id INTEGER NOT NULL,
  service_type VARCHAR(50) NOT NULL DEFAULT '',
  problem_desc TEXT NOT NULL,
  calculated_fee NUMERIC(10,2),
  mobilization_fee NUMERIC(10,2) DEFAULT 0.00,
  labor_materials_cost NUMERIC(10,2) DEFAULT 0.00,
  total_final_cost NUMERIC(10,2) DEFAULT 0.00,
  final_payment_status TEXT DEFAULT 'pending' CHECK (final_payment_status IN ('pending','paid','failed')),
  final_payment_qr TEXT,
  final_payment_xendit_id VARCHAR(100),
  final_payment_paid_at TIMESTAMP,
  labor_cost NUMERIC(10,2) DEFAULT 0.00,
  materials_cost NUMERIC(10,2) DEFAULT 0.00,
  admin_fee_percentage NUMERIC(5,2) DEFAULT 4.00,
  admin_fee_amount NUMERIC(10,2) DEFAULT 0.00,
  latitude NUMERIC(10,8),
  longitude NUMERIC(11,8),
  location_address VARCHAR(255),
  urgency_level TEXT DEFAULT 'Normal' CHECK (urgency_level IN ('Normal','High','Emergency')),
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending','Accepted','Declined','Pending Confirmation','Completed','Cancelled')),
  booking_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  payment_method VARCHAR(20) DEFAULT 'Cash',
  payment_status VARCHAR(20) DEFAULT 'Pending',
  wallet_credited BOOLEAN DEFAULT FALSE,
  fee_deducted BOOLEAN DEFAULT FALSE,
  is_escrow BOOLEAN DEFAULT FALSE,
  escrow_status TEXT DEFAULT 'held' CHECK (escrow_status IN ('held','released','refunded')),
  escrow_released_at TIMESTAMP,
  client_confirmed_at TIMESTAMP,
  completion_proof_submitted BOOLEAN DEFAULT FALSE,
  completion_proof_verified_at TIMESTAMP,
  transaction_id VARCHAR(100),
  checkout_url TEXT,
  qr_code VARCHAR(255),
  xendit_payment_id VARCHAR(100),
  xendit_paid_at TIMESTAMP,
  final_commission_deducted BOOLEAN NOT NULL DEFAULT FALSE,
  final_payment_method VARCHAR(20),
  greenloop_prompted BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
);
COMMENT ON COLUMN bookings.admin_fee_percentage IS '4% platform commission on labor fee';
COMMENT ON COLUMN bookings.greenloop_prompted IS 'Whether client was shown the GreenLoop scrap opt-in after completion';

CREATE TABLE employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  employee_code VARCHAR(20) NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(150),
  phone VARCHAR(20),
  address TEXT,
  "position" VARCHAR(100) NOT NULL,
  department TEXT NOT NULL DEFAULT 'Other' CHECK (department IN ('Management','Finance','HR','Tech','Operations','Support','Other')),
  employment_type TEXT NOT NULL DEFAULT 'Full-time' CHECK (employment_type IN ('Full-time','Part-time','Contractual','Freelancer')),
  employment_status TEXT NOT NULL DEFAULT 'Active' CHECK (employment_status IN ('Active','On Leave','Terminated','Resigned')),
  date_hired DATE NOT NULL,
  date_ended DATE,
  basic_salary NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  pay_frequency TEXT NOT NULL DEFAULT 'Monthly' CHECK (pay_frequency IN ('Monthly','Semi-monthly','Weekly')),
  sss_number VARCHAR(30),
  philhealth_number VARCHAR(30),
  pagibig_number VARCHAR(30),
  tin_number VARCHAR(30),
  bank_name VARCHAR(100),
  bank_account VARCHAR(50),
  gcash_number VARCHAR(20),
  profile_pic VARCHAR(255),
  notes TEXT,
  added_by INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (employee_code)
);
COMMENT ON TABLE employees IS 'Internal Abilisto staff — separate from platform workers';
COMMENT ON COLUMN employees.date_ended IS 'NULL if still active';
COMMENT ON COLUMN employees.added_by IS 'hr user_id who added this employee';

CREATE TABLE fee_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  booking_id INTEGER NOT NULL,
  subtotal NUMERIC(10,2),
  discount NUMERIC(10,2),
  total NUMERIC(10,2),
  calculated_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE green_coin_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('earn','spend','refund','expired')),
  amount NUMERIC(10,2) NOT NULL,
  balance_after NUMERIC(10,2) NOT NULL,
  reference_type TEXT NOT NULL CHECK (reference_type IN ('scrap_report','reward_redemption','admin_adjustment')),
  reference_id INTEGER,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON TABLE green_coin_transactions IS 'Full audit log of Green Coin earn and spend events';
COMMENT ON COLUMN green_coin_transactions.reference_id IS 'greenloop_reports.id or greenloop_redemptions.id';

CREATE TABLE green_coins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  balance NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_earned NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_spent NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (user_id)
);
COMMENT ON TABLE green_coins IS 'Green Coin balance per client user';

CREATE TABLE greenloop_accepted_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  category VARCHAR(100) NOT NULL,
  item_name VARCHAR(150) NOT NULL,
  description TEXT,
  unit VARCHAR(50) DEFAULT 'piece',
  green_coins_per_unit NUMERIC(8,2) NOT NULL DEFAULT 10.00,
  estimated_value_min NUMERIC(8,2),
  estimated_value_max NUMERIC(8,2),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  icon VARCHAR(50) DEFAULT 'recycle',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);
COMMENT ON TABLE greenloop_accepted_items IS 'Predefined list of accepted scrap items for GreenLoop';
COMMENT ON COLUMN greenloop_accepted_items.green_coins_per_unit IS 'Green Coins earned per unit turned in';
COMMENT ON COLUMN greenloop_accepted_items.estimated_value_min IS 'Estimated PHP scrap value minimum';
COMMENT ON COLUMN greenloop_accepted_items.estimated_value_max IS 'Estimated PHP scrap value maximum';

CREATE TABLE greenloop_broadcast_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  report_id INTEGER NOT NULL,
  junkshop_id INTEGER NOT NULL,
  seen_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (report_id, junkshop_id)
);

CREATE TABLE greenloop_redemptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  reward_id INTEGER NOT NULL,
  green_coins_spent NUMERIC(8,2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','used','expired','cancelled')),
  promo_code VARCHAR(20),
  used_at TIMESTAMP,
  used_booking_id INTEGER,
  expires_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON COLUMN greenloop_redemptions.promo_code IS 'Generated code to apply discount';

CREATE TABLE greenloop_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  client_id INTEGER NOT NULL,
  booking_id INTEGER,
  item_id INTEGER,
  item_name_custom VARCHAR(200),
  quantity NUMERIC(8,2) NOT NULL DEFAULT 1.00,
  unit VARCHAR(50) DEFAULT 'piece',
  ai_assessment TEXT,
  ai_accepted BOOLEAN,
  estimated_green_coins NUMERIC(8,2) DEFAULT 0.00,
  actual_green_coins_awarded NUMERIC(8,2) DEFAULT 0.00,
  client_notes TEXT,
  pickup_latitude NUMERIC(10,8),
  pickup_longitude NUMERIC(11,8),
  pickup_address VARCHAR(500),
  image_path VARCHAR(255),
  rejection_reason TEXT,
  junkshop_id INTEGER,
  broadcasted_at TIMESTAMP,
  accepted_at TIMESTAMP,
  completed_at TIMESTAMP,
  photo_path VARCHAR(255),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','broadcasted','accepted','completed','scheduled','collected','verified','rejected','cancelled','')),
  admin_notes TEXT,
  pickup_scheduled_at TIMESTAMP,
  collected_at TIMESTAMP,
  verified_at TIMESTAMP,
  verified_by INTEGER,
  coins_awarded_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);
COMMENT ON TABLE greenloop_reports IS 'Scrap turn-in reports submitted by clients';
COMMENT ON COLUMN greenloop_reports.booking_id IS 'The completed booking that triggered this';
COMMENT ON COLUMN greenloop_reports.item_id IS 'FK to greenloop_accepted_items; NULL if AI-identified custom item';
COMMENT ON COLUMN greenloop_reports.item_name_custom IS 'If user described an item not in catalog';
COMMENT ON COLUMN greenloop_reports.ai_assessment IS 'Raw AI response for this item';
COMMENT ON COLUMN greenloop_reports.ai_accepted IS 'true=AI said accepted, false=not accepted, NULL=not AI-assessed';
COMMENT ON COLUMN greenloop_reports.client_notes IS 'Optional notes from client';
COMMENT ON COLUMN greenloop_reports.pickup_latitude IS 'GPS latitude of pickup location';
COMMENT ON COLUMN greenloop_reports.pickup_longitude IS 'GPS longitude of pickup location';
COMMENT ON COLUMN greenloop_reports.pickup_address IS 'Human-readable pickup address';
COMMENT ON COLUMN greenloop_reports.photo_path IS 'Optional photo upload';

CREATE TABLE greenloop_rewards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  reward_name VARCHAR(150) NOT NULL,
  description TEXT,
  green_coins_cost NUMERIC(8,2) NOT NULL,
  reward_type TEXT NOT NULL DEFAULT 'booking_discount' CHECK (reward_type IN ('booking_discount','free_booking','cash_credit','other')),
  reward_value NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  stock INTEGER,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  valid_days INTEGER DEFAULT 30,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON TABLE greenloop_rewards IS 'Rewards that can be redeemed with Green Coins';
COMMENT ON COLUMN greenloop_rewards.reward_name IS 'e.g. ₱30 Booking Fee Discount';
COMMENT ON COLUMN greenloop_rewards.green_coins_cost IS 'How many Green Coins to redeem';
COMMENT ON COLUMN greenloop_rewards.reward_value IS 'PHP value of the reward';
COMMENT ON COLUMN greenloop_rewards.stock IS 'NULL = unlimited';
COMMENT ON COLUMN greenloop_rewards.valid_days IS 'Days the reward is valid after redemption';

CREATE TABLE hr_permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  permission VARCHAR(100) NOT NULL,
  granted_by INTEGER,
  granted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE ip_whitelist (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ip_address VARCHAR(45) NOT NULL,
  description VARCHAR(255),
  created_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (ip_address)
);

CREATE TABLE job_broadcasts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  client_id INTEGER NOT NULL,
  service_category VARCHAR(50),
  category VARCHAR(50) NOT NULL,
  problem_tags TEXT,
  urgency TEXT DEFAULT 'Normal' CHECK (urgency IN ('Normal','High','Emergency','')),
  latitude NUMERIC(10,8),
  longitude NUMERIC(11,8),
  client_lat NUMERIC(10,8),
  client_lng NUMERIC(11,8),
  location_address VARCHAR(255),
  status TEXT DEFAULT 'searching' CHECK (status IN ('searching','accepted','expired','cancelled')),
  accepted_worker_id INTEGER,
  accepted_booking_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP,
  is_quick_match BOOLEAN DEFAULT TRUE,
  candidate_workers TEXT,
  declined_workers TEXT,
  PRIMARY KEY (id)
);
COMMENT ON COLUMN job_broadcasts.location_address IS 'Human-readable address resolved from client lat/lng at broadcast time';
COMMENT ON COLUMN job_broadcasts.candidate_workers IS 'JSON array of worker IDs that were selected';
COMMENT ON COLUMN job_broadcasts.declined_workers IS 'JSON array of workers who declined or timed out';

CREATE TABLE job_candidates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  broadcast_id INTEGER NOT NULL,
  worker_id INTEGER NOT NULL,
  score NUMERIC(10,2),
  PRIMARY KEY (id)
);

CREATE TABLE job_completion_proofs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  booking_id INTEGER NOT NULL,
  worker_id INTEGER NOT NULL,
  proof_type TEXT NOT NULL CHECK (proof_type IN ('photo','video','document')),
  file_path VARCHAR(500) NOT NULL,
  description TEXT,
  submitted_at TIMESTAMP NOT NULL,
  admin_verified_at TIMESTAMP,
  admin_notes TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  PRIMARY KEY (id)
);

CREATE TABLE junkshop_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  junkshop_id INTEGER NOT NULL,
  token VARCHAR(128) NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (token)
);

CREATE TABLE junkshops (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  shop_name VARCHAR(150) NOT NULL,
  owner_name VARCHAR(150) NOT NULL,
  email VARCHAR(191) NOT NULL,
  password VARCHAR(255) NOT NULL,
  contact_number VARCHAR(20),
  shop_address TEXT,
  coverage_area VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (email)
);

CREATE TABLE messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  booking_id INTEGER NOT NULL,
  sender_id INTEGER NOT NULL,
  message TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text','image','video')),
  "timestamp" TIMESTAMP NOT NULL DEFAULT NOW(),
  attachment_path VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  message VARCHAR(255) NOT NULL,
  link VARCHAR(255) DEFAULT '#',
  is_read SMALLINT DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE payroll_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(150) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  pay_date DATE NOT NULL,
  pay_frequency TEXT NOT NULL DEFAULT 'Monthly' CHECK (pay_frequency IN ('Monthly','Semi-monthly','Weekly')),
  status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','For Approval','Approved','Released','Cancelled')),
  total_gross NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  total_deductions NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  total_net NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  employee_count INTEGER NOT NULL DEFAULT 0,
  expense_id INTEGER,
  notes TEXT,
  generated_by INTEGER NOT NULL,
  approved_by INTEGER,
  approved_at TIMESTAMP,
  released_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);
COMMENT ON TABLE payroll_runs IS 'Each payroll generation cycle';
COMMENT ON COLUMN payroll_runs.title IS 'e.g. March 2026 — Full Month';
COMMENT ON COLUMN payroll_runs.expense_id IS 'admin_expenses.id — set when released to finance';
COMMENT ON COLUMN payroll_runs.generated_by IS 'hr user_id';
COMMENT ON COLUMN payroll_runs.approved_by IS 'hr/admin user_id who approved';

CREATE TABLE payroll_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  payroll_run_id INTEGER NOT NULL,
  employee_id INTEGER NOT NULL,
  basic_pay NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  overtime_hours NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  overtime_pay NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  holiday_pay NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  allowances NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  bonuses NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  gross_pay NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  sss_ee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  sss_er NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  philhealth_ee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  philhealth_er NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  pagibig_ee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  pagibig_er NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  withholding_tax NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  late_deduction NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  absent_deduction NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  other_deductions NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_deductions NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  net_pay NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  days_worked NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  days_absent NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  days_leave NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (payroll_run_id, employee_id)
);
COMMENT ON TABLE payroll_items IS 'Per-employee breakdown for each payroll run';
COMMENT ON COLUMN payroll_items.sss_ee IS 'SSS Employee share';
COMMENT ON COLUMN payroll_items.sss_er IS 'SSS Employer share';
COMMENT ON COLUMN payroll_items.philhealth_ee IS 'PhilHealth Employee';
COMMENT ON COLUMN payroll_items.philhealth_er IS 'PhilHealth Employer';
COMMENT ON COLUMN payroll_items.pagibig_ee IS 'Pag-IBIG Employee';
COMMENT ON COLUMN payroll_items.pagibig_er IS 'Pag-IBIG Employer';

CREATE TABLE portfolio_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE post_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE post_likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (post_id, user_id)
);

CREATE TABLE report_replies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  report_id INTEGER NOT NULL,
  report_type TEXT NOT NULL CHECK (report_type IN ('client','worker')),
  sender_id INTEGER NOT NULL,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('admin','client','worker','support')),
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON TABLE report_replies IS 'Threaded reply system for report communications';
COMMENT ON COLUMN report_replies.report_id IS 'references reports.id or reports_worker.id';
COMMENT ON COLUMN report_replies.sender_id IS 'user_id of sender (admin or user)';

CREATE TABLE reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  booking_id INTEGER NOT NULL,
  client_id INTEGER NOT NULL,
  worker_id INTEGER NOT NULL,
  report_reason VARCHAR(50) NOT NULL,
  report_details TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','reviewed','resolved','dismissed')),
  admin_notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE reports_worker (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  worker_id INTEGER NOT NULL,
  reported_user_id INTEGER NOT NULL,
  reported_user_role TEXT NOT NULL CHECK (reported_user_role IN ('client','worker','business')),
  booking_id INTEGER,
  report_reason VARCHAR(50) NOT NULL,
  report_details TEXT,
  proof_image VARCHAR(255),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','reviewed','resolved','dismissed')),
  admin_notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  booking_id INTEGER NOT NULL,
  worker_id INTEGER NOT NULL,
  client_id INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  setting_key VARCHAR(100) NOT NULL,
  setting_value TEXT,
  description TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (setting_key)
);

CREATE TABLE system_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  action VARCHAR(100) NOT NULL,
  details TEXT,
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE top_ups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  worker_id INTEGER NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('gcash','bank')),
  reference_number VARCHAR(100),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','completed','failed')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  google_id VARCHAR(255),
  avatar VARCHAR(500),
  password VARCHAR(255),
  verification_token VARCHAR(255),
  is_email_verified BOOLEAN DEFAULT FALSE,
  phone VARCHAR(20) NOT NULL,
  address VARCHAR(255) NOT NULL,
  municipality TEXT NOT NULL CHECK (municipality IN ('Carrascal','Cantilan','Madrid','Carmen','Lanuza','')),
  role TEXT NOT NULL CHECK (role IN ('admin','worker','client','business','hr','finance')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  latitude NUMERIC(10,8),
  longitude NUMERIC(11,8),
  t_latitude NUMERIC(10,8),
  t_longitude NUMERIC(11,8),
  verification_code VARCHAR(6),
  is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  birthdate DATE,
  profile_pic VARCHAR(255),
  is_new BOOLEAN NOT NULL DEFAULT TRUE,
  fcm_token TEXT,
  cash_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  location_sharing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  has_seen_tour BOOLEAN DEFAULT FALSE,
  has_seen_booking_tour BOOLEAN DEFAULT FALSE,
  google_temp_token VARCHAR(64),
  google_temp_token_expires TIMESTAMP,
  is_flagged BOOLEAN NOT NULL DEFAULT FALSE,
  violation_count INTEGER NOT NULL DEFAULT 0,
  last_violation_at TIMESTAMP,
  has_prior_violation BOOLEAN NOT NULL DEFAULT FALSE,
  cash_restriction_at TIMESTAMP,
  appeal_eligible BOOLEAN NOT NULL DEFAULT TRUE,
  appeal_deadline TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (email)
);
COMMENT ON COLUMN users.is_new IS 'Set to false after first profile setup is completed or skipped';
COMMENT ON COLUMN users.location_sharing_enabled IS 'Worker opt-in to share approximate location on We Map. false=disabled (default), true=enabled';
COMMENT ON COLUMN users.is_flagged IS 'true = has at least one unresolved/confirmed report';
COMMENT ON COLUMN users.violation_count IS 'Consecutive confirmed violations (resets on appeal success)';
COMMENT ON COLUMN users.has_prior_violation IS 'true = has ever had a confirmed violation; affects appeal eligibility';
COMMENT ON COLUMN users.cash_restriction_at IS 'When cash payment was restricted';
COMMENT ON COLUMN users.appeal_eligible IS 'false = no longer eligible for 48-hour appeal window';
COMMENT ON COLUMN users.appeal_deadline IS 'NULL if no active appeal window or not eligible';

CREATE TABLE verification (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  last_name VARCHAR(100) NOT NULL,
  age INTEGER,
  nationality VARCHAR(100) NOT NULL,
  civil_status TEXT NOT NULL CHECK (civil_status IN ('Single','Married','Divorced','Widowed','Separated')),
  date_of_birth DATE NOT NULL,
  place_of_birth VARCHAR(255) NOT NULL,
  sex TEXT NOT NULL CHECK (sex IN ('Male','Female','Other')),
  permanent_region VARCHAR(100) DEFAULT 'Surigao del Sur',
  permanent_municipality VARCHAR(100) NOT NULL,
  permanent_barangay VARCHAR(100) NOT NULL,
  permanent_street VARCHAR(255),
  permanent_house_details VARCHAR(255),
  current_region VARCHAR(100) DEFAULT 'Surigao del Sur',
  current_municipality VARCHAR(100) NOT NULL,
  current_barangay VARCHAR(100) NOT NULL,
  current_street VARCHAR(255),
  current_house_details VARCHAR(255),
  same_as_permanent BOOLEAN DEFAULT FALSE,
  zip_code VARCHAR(20) NOT NULL,
  id_type TEXT NOT NULL CHECK (id_type IN ('Passport','SSS ID','GSIS ID','Driver''s License','PhilHealth ID','Voter''s ID','PRC ID','Postal ID','National ID','Barangay ID','ePhilID','Drivers License','UMID','PRC','Student ID')),
  id_number VARCHAR(100),
  id_photo_front VARCHAR(255),
  id_photo_back VARCHAR(255),
  face_photo VARCHAR(255),
  id_extracted_data TEXT CHECK (id_extracted_data IS NULL OR id_extracted_data IS JSON),
  id_verified BOOLEAN DEFAULT FALSE,
  id_verification_notes TEXT,
  has_nc_certificate BOOLEAN DEFAULT FALSE,
  verification_step INTEGER DEFAULT 1,
  verification_status TEXT DEFAULT 'pending' CHECK (verification_status IN ('pending','processing','verified','rejected')),
  rejection_reason TEXT,
  submitted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  verified_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE verification_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  verification_id INTEGER,
  worker_id INTEGER NOT NULL,
  document_type VARCHAR(50) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  extracted_data TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','pending_review','verified','rejected')),
  admin_notes TEXT,
  uploaded_at TIMESTAMP NOT NULL,
  verified_at TIMESTAMP,
  skill_sub_category VARCHAR(100),
  nc_level TEXT CHECK (nc_level IN ('NC I','NC II','NC III')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON COLUMN verification_documents.verification_id IS 'FK to verification.id — NULL for legacy rows';

CREATE TABLE verification_nc_skills (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  verification_id INTEGER NOT NULL,
  worker_id INTEGER NOT NULL,
  sub_category VARCHAR(100) NOT NULL,
  main_category VARCHAR(100),
  nc_level TEXT NOT NULL CHECK (nc_level IN ('NC I','NC II','NC III')),
  nc_certificate_number VARCHAR(512),
  nc_certificate_image VARCHAR(255),
  badge_level TEXT NOT NULL DEFAULT 'Unverified' CHECK (badge_level IN ('Bronze','Silver','Gold','Community','Unverified')),
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMP,
  verification_notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (verification_id, sub_category)
);
COMMENT ON TABLE verification_nc_skills IS 'Per-skill NC certificates linked to a KYC verification submission';
COMMENT ON COLUMN verification_nc_skills.nc_certificate_number IS 'AES-256-GCM encrypted';
COMMENT ON COLUMN verification_nc_skills.nc_certificate_image IS 'Relative path in private_uploads/';

CREATE TABLE verification_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  worker_id INTEGER NOT NULL,
  document_type VARCHAR(50) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  status VARCHAR(20) DEFAULT 'Pending',
  reviewed_at TIMESTAMP,
  reviewed_by INTEGER,
  admin_notes TEXT,
  uploaded_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE violation_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  user_role TEXT NOT NULL CHECK (user_role IN ('worker','client')),
  report_id INTEGER NOT NULL,
  report_type TEXT NOT NULL CHECK (report_type IN ('client','worker')),
  violation_num INTEGER NOT NULL,
  action_taken TEXT NOT NULL CHECK (action_taken IN ('warning','booking_blocked','account_deleted','cash_restricted','cash_restriction_lifted')),
  notes TEXT,
  actioned_by INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
COMMENT ON TABLE violation_logs IS 'Audit log of all penalty actions taken';
COMMENT ON COLUMN violation_logs.violation_num IS '1=warning, 2=block, 3=delete';
COMMENT ON COLUMN violation_logs.actioned_by IS 'support admin user_id';

CREATE TABLE wallet_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  user_type TEXT NOT NULL CHECK (user_type IN ('worker','admin')),
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('credit','debit','fee','refund','withdrawal')),
  amount NUMERIC(10,2) NOT NULL,
  reference_id INTEGER,
  reference_type TEXT CHECK (reference_type IS NULL OR reference_type IN ('booking','withdrawal','fee','topup','listo_points','listo_reward','final_commission','final_payment','')),
  description TEXT,
  balance_after NUMERIC(10,2),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  PRIMARY KEY (id)
);
COMMENT ON COLUMN wallet_transactions.reference_id IS 'booking_id or withdrawal_id';

CREATE TABLE withdrawals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  worker_id INTEGER NOT NULL,
  booking_id INTEGER,
  amount NUMERIC(10,2) NOT NULL,
  gcash_number VARCHAR(15) NOT NULL,
  xendit_disbursement_id VARCHAR(100),
  status VARCHAR(20) DEFAULT 'Pending',
  processed_at TIMESTAMP,
  notes TEXT,
  request_date TIMESTAMP DEFAULT NOW(),
  approved_by INTEGER,
  rejection_note TEXT,
  PRIMARY KEY (id)
);
COMMENT ON COLUMN withdrawals.booking_id IS 'Reference booking for cost breakdown display';
COMMENT ON COLUMN withdrawals.xendit_disbursement_id IS 'Xendit disbursement ID returned by API';
COMMENT ON COLUMN withdrawals.processed_at IS 'When admin approved & Xendit was called';
COMMENT ON COLUMN withdrawals.notes IS 'Failure reason or admin notes';
COMMENT ON COLUMN withdrawals.approved_by IS 'hr user_id';

CREATE TABLE worker_docs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  doc_type TEXT NOT NULL CHECK (doc_type IN ('Valid ID','NC I','NC II','NC III')),
  file_path VARCHAR(255) NOT NULL,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending','Verified','Rejected')),
  uploaded_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE TABLE worker_profiles (
  user_id INTEGER NOT NULL,
  service_category VARCHAR(50) NOT NULL,
  bio TEXT,
  is_tesda_verified BOOLEAN DEFAULT FALSE,
  vouch_count INTEGER DEFAULT 0,
  average_rating NUMERIC(3,2) DEFAULT 0.00,
  availability_status TEXT DEFAULT 'Available' CHECK (availability_status IN ('Available','Busy')),
  schedule_mode TEXT NOT NULL DEFAULT 'manual' CHECK (schedule_mode IN ('manual','scheduled')),
  schedule_days VARCHAR(20),
  schedule_time_start TIME,
  schedule_time_end TIME,
  schedule_label VARCHAR(100),
  can_accept_bookings BOOLEAN NOT NULL DEFAULT TRUE,
  wallet_balance NUMERIC(10,2) DEFAULT 0.00,
  free_credits NUMERIC(10,2) DEFAULT 100.00,
  free_bookings_used INTEGER DEFAULT 0,
  listo_points INTEGER DEFAULT 0,
  rating_count INTEGER DEFAULT 0,
  verification_status TEXT DEFAULT 'Unverified' CHECK (verification_status IN ('Unverified','Bronze','Silver','Gold','Community')),
  is_verified BOOLEAN DEFAULT FALSE,
  jobs_completed INTEGER DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  minimum_standard_rate NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  skill_count SMALLINT NOT NULL DEFAULT 0,
  deletion_pending BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (user_id)
);
COMMENT ON COLUMN worker_profiles.schedule_mode IS 'manual = old toggle, scheduled = rule-based auto on/off';
COMMENT ON COLUMN worker_profiles.schedule_days IS 'Comma-separated day numbers: 0=Sun,1=Mon,...,6=Sat  e.g. "1,2,3,4,5"';
COMMENT ON COLUMN worker_profiles.schedule_time_start IS 'Daily start time for availability window e.g. 08:00:00';
COMMENT ON COLUMN worker_profiles.schedule_time_end IS 'Daily end time  e.g. 17:00:00';
COMMENT ON COLUMN worker_profiles.schedule_label IS 'Human-readable label saved by worker e.g. "Weekdays 8 AM – 5 PM"';
COMMENT ON COLUMN worker_profiles.can_accept_bookings IS 'false = admin has disabled this worker from accepting new bookings';
COMMENT ON COLUMN worker_profiles.minimum_standard_rate IS 'Worker declared minimum labor charge per job';
COMMENT ON COLUMN worker_profiles.skill_count IS 'Denormalised count of worker_skills rows (max 3)';
COMMENT ON COLUMN worker_profiles.deletion_pending IS 'true = scheduled for deletion on next admin confirmation';

CREATE TABLE worker_skills (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  worker_id INTEGER NOT NULL,
  sub_category VARCHAR(100) NOT NULL,
  main_category VARCHAR(100) NOT NULL,
  nc_level TEXT CHECK (nc_level IN ('NC I','NC II','NC III')),
  nc_certificate_number VARCHAR(512),
  badge_level TEXT NOT NULL DEFAULT 'Unverified' CHECK (badge_level IN ('Unverified','Bronze','Silver','Gold','Community')),
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  verification_notes TEXT,
  verified_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP,
  nc_certificate_image VARCHAR(255),
  PRIMARY KEY (id),
  UNIQUE (worker_id, sub_category)
);
COMMENT ON COLUMN worker_skills.sub_category IS 'e.g. Electrical, Videography';
COMMENT ON COLUMN worker_skills.main_category IS 'e.g. Construction & Trades';
COMMENT ON COLUMN worker_skills.nc_certificate_number IS 'AES-256-GCM encrypted NC certificate number';
COMMENT ON COLUMN worker_skills.nc_certificate_image IS 'Relative path in private_uploads/nc_certificates/';

-- ── 2. updated_at TRIGGER FUNCTION + PER-TABLE TRIGGERS ─────

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_admin_expenses_updated_at BEFORE UPDATE ON admin_expenses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_admin_wallet_updated_at BEFORE UPDATE ON admin_wallet FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_bookings_updated_at BEFORE UPDATE ON bookings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON employees FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_green_coins_updated_at BEFORE UPDATE ON green_coins FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_greenloop_accepted_items_updated_at BEFORE UPDATE ON greenloop_accepted_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_greenloop_reports_updated_at BEFORE UPDATE ON greenloop_reports FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_junkshops_updated_at BEFORE UPDATE ON junkshops FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_payroll_runs_updated_at BEFORE UPDATE ON payroll_runs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_reports_updated_at BEFORE UPDATE ON reports FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_reports_worker_updated_at BEFORE UPDATE ON reports_worker FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_verification_updated_at BEFORE UPDATE ON verification FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_verification_nc_skills_updated_at BEFORE UPDATE ON verification_nc_skills FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_wallet_transactions_updated_at BEFORE UPDATE ON wallet_transactions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_worker_skills_updated_at BEFORE UPDATE ON worker_skills FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Business-logic triggers (MySQL originals used session vars @service_name /
-- @current_user_id / @current_ip; Postgres equivalent is set_config()/
-- current_setting(), set from PHP right before the UPDATE that needs it).

CREATE OR REPLACE FUNCTION trg_after_service_settings_update() RETURNS TRIGGER AS $$
DECLARE
  service_name TEXT;
BEGIN
  IF NEW.setting_key LIKE 'service_%' THEN
    service_name := REPLACE(NEW.setting_key, 'service_', '');
    service_name := REPLACE(service_name, '_', ' ');
    UPDATE worker_profiles
    SET is_active = (NEW.setting_value = '1')
    WHERE service_category = service_name;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_service_settings_update AFTER UPDATE ON settings
FOR EACH ROW EXECUTE FUNCTION trg_after_service_settings_update();

CREATE OR REPLACE FUNCTION trg_after_settings_update() RETURNS TRIGGER AS $$
DECLARE
  v_user_id INTEGER;
  v_ip_addr TEXT;
BEGIN
  v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::INTEGER;
  v_ip_addr := current_setting('app.current_ip', true);

  IF v_user_id IS NOT NULL THEN
    INSERT INTO system_logs (user_id, action, details, ip_address, created_at)
    VALUES (
      v_user_id,
      'update_settings',
      'Setting changed: ' || NEW.setting_key || ' from "' || OLD.setting_value || '" to "' || NEW.setting_value || '"',
      v_ip_addr,
      NOW()
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_settings_update AFTER UPDATE ON settings
FOR EACH ROW EXECUTE FUNCTION trg_after_settings_update();

CREATE OR REPLACE FUNCTION trg_ws_after_insert() RETURNS TRIGGER AS $$
BEGIN
  UPDATE worker_profiles SET skill_count = skill_count + 1 WHERE user_id = NEW.worker_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ws_after_insert AFTER INSERT ON worker_skills
FOR EACH ROW EXECUTE FUNCTION trg_ws_after_insert();

CREATE OR REPLACE FUNCTION trg_ws_after_delete() RETURNS TRIGGER AS $$
BEGIN
  UPDATE worker_profiles SET skill_count = skill_count - 1 WHERE user_id = OLD.worker_id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ws_after_delete AFTER DELETE ON worker_skills
FOR EACH ROW EXECUTE FUNCTION trg_ws_after_delete();

-- ── 3. VIEWS ─────────────────────────────────────────────────

CREATE VIEW v_worker_skill_badges AS
SELECT
  ws.worker_id,
  u.full_name AS worker_name,
  ws.sub_category,
  ws.main_category,
  ws.badge_level,
  ws.nc_level,
  ws.nc_certificate_number,
  ws.nc_certificate_image,
  ws.is_verified,
  ws.verification_notes,
  ws.verified_at,
  v.id AS verification_id,
  v.verification_status,
  vns.id AS nc_submission_id,
  vns.nc_level AS submitted_nc_level,
  vns.badge_level AS submitted_badge_level,
  vns.is_verified AS nc_submission_verified
FROM worker_skills ws
JOIN users u ON u.id = ws.worker_id
LEFT JOIN verification v ON v.user_id = ws.worker_id AND v.verification_status IN ('pending','processing')
LEFT JOIN verification_nc_skills vns ON vns.verification_id = v.id AND vns.sub_category = ws.sub_category;

CREATE VIEW v_worker_skill_summary AS
SELECT
  u.id AS worker_id,
  u.full_name,
  u.municipality,
  wp.average_rating,
  wp.jobs_completed,
  wp.skill_count,
  STRING_AGG(ws.sub_category || ' [' || ws.badge_level || ']', ' · ' ORDER BY ws.badge_level DESC) AS skills_and_badges
FROM users u
JOIN worker_profiles wp ON wp.user_id = u.id
LEFT JOIN worker_skills ws ON ws.worker_id = u.id
WHERE u.role = 'worker'
GROUP BY u.id, u.full_name, u.municipality, wp.average_rating, wp.jobs_completed, wp.skill_count;

-- ── 4. INDEXES (non-PK, non-UNIQUE-already-inline) ──────────

CREATE INDEX idx_admin_expenses_type ON admin_expenses (expense_type);
CREATE INDEX idx_admin_expenses_date ON admin_expenses (expense_date);
CREATE INDEX idx_admin_expenses_logged_by ON admin_expenses (logged_by);

CREATE INDEX idx_bookings_client_id ON bookings (client_id);
CREATE INDEX idx_bookings_worker_id ON bookings (worker_id);
CREATE INDEX idx_bookings_status_worker ON bookings (status, worker_id);
CREATE INDEX idx_bookings_broadcast ON bookings (broadcast_id);

CREATE INDEX idx_employees_department ON employees (department);
CREATE INDEX idx_employees_status ON employees (employment_status);
CREATE INDEX idx_employees_added_by ON employees (added_by);

CREATE INDEX idx_fee_logs_booking_id ON fee_logs (booking_id);

CREATE INDEX idx_gct_user_id ON green_coin_transactions (user_id);

CREATE INDEX idx_glred_user_id ON greenloop_redemptions (user_id);
CREATE INDEX idx_glred_reward_id ON greenloop_redemptions (reward_id);

CREATE INDEX idx_glr_client_id ON greenloop_reports (client_id);
CREATE INDEX idx_glr_booking_id ON greenloop_reports (booking_id);
CREATE INDEX idx_glr_status ON greenloop_reports (status);
CREATE INDEX idx_glr_item_id ON greenloop_reports (item_id);
CREATE INDEX idx_glr_junkshop_id ON greenloop_reports (junkshop_id);

CREATE INDEX idx_hr_permissions_user_id ON hr_permissions (user_id);
CREATE INDEX idx_hr_permissions_permission ON hr_permissions (permission);

CREATE INDEX idx_ip_whitelist_created_by ON ip_whitelist (created_by);

CREATE INDEX idx_job_broadcasts_quick_match ON job_broadcasts (status, is_quick_match, expires_at);

CREATE INDEX idx_job_candidates_broadcast_id ON job_candidates (broadcast_id);

CREATE INDEX idx_jcp_booking_id ON job_completion_proofs (booking_id);
CREATE INDEX idx_jcp_worker_id ON job_completion_proofs (worker_id);

CREATE INDEX idx_junkshop_sessions_shop_id ON junkshop_sessions (junkshop_id);

CREATE INDEX idx_messages_booking_id ON messages (booking_id);
CREATE INDEX idx_messages_sender_id ON messages (sender_id);

CREATE INDEX idx_notifications_user_id ON notifications (user_id);

CREATE INDEX idx_payroll_items_employee ON payroll_items (employee_id);

CREATE INDEX idx_payroll_runs_status ON payroll_runs (status);
CREATE INDEX idx_payroll_runs_period ON payroll_runs (period_start, period_end);
CREATE INDEX idx_payroll_runs_expense ON payroll_runs (expense_id);

CREATE INDEX idx_portfolio_images_user_id ON portfolio_images (user_id);

CREATE INDEX idx_post_comments_post_id ON post_comments (post_id);
CREATE INDEX idx_post_comments_user_id ON post_comments (user_id);

CREATE INDEX idx_post_likes_user_id ON post_likes (user_id);

CREATE INDEX idx_report_replies_report ON report_replies (report_id, report_type);
CREATE INDEX idx_report_replies_sender ON report_replies (sender_id);
CREATE INDEX idx_report_replies_created ON report_replies (created_at);

CREATE INDEX idx_reports_booking_id ON reports (booking_id);
CREATE INDEX idx_reports_client_id ON reports (client_id);
CREATE INDEX idx_reports_worker_id ON reports (worker_id);
CREATE INDEX idx_reports_status ON reports (status);

CREATE INDEX idx_reports_worker_worker_id ON reports_worker (worker_id);
CREATE INDEX idx_reports_worker_reported_user_id ON reports_worker (reported_user_id);
CREATE INDEX idx_reports_worker_booking_id ON reports_worker (booking_id);
CREATE INDEX idx_reports_worker_status ON reports_worker (status);

CREATE INDEX idx_system_logs_user_id ON system_logs (user_id);
CREATE INDEX idx_system_logs_created_at ON system_logs (created_at);

CREATE INDEX idx_top_ups_worker_id ON top_ups (worker_id);

CREATE INDEX idx_verification_status ON verification (verification_status);
CREATE INDEX idx_verification_user ON verification (user_id);

CREATE INDEX idx_verification_documents_worker_id ON verification_documents (worker_id);
CREATE INDEX idx_verification_documents_ver_id ON verification_documents (verification_id);

CREATE INDEX idx_vncs_worker_sub ON verification_nc_skills (worker_id, sub_category);
CREATE INDEX idx_vncs_ver_id ON verification_nc_skills (verification_id);
CREATE INDEX idx_vncs_badge_level ON verification_nc_skills (badge_level);

CREATE INDEX idx_verification_requests_reviewed_by ON verification_requests (reviewed_by);

CREATE INDEX idx_violation_logs_user ON violation_logs (user_id);
CREATE INDEX idx_violation_logs_report ON violation_logs (report_id, report_type);

CREATE INDEX idx_wallet_transactions_user_id ON wallet_transactions (user_id);
CREATE INDEX idx_wallet_transactions_reference_id ON wallet_transactions (reference_id);
CREATE INDEX idx_wallet_transactions_user_ref ON wallet_transactions (user_id, reference_type);

CREATE INDEX idx_withdrawals_xendit_disbursement ON withdrawals (xendit_disbursement_id);
CREATE INDEX idx_withdrawals_approved_by ON withdrawals (approved_by);

CREATE INDEX idx_worker_docs_user_id ON worker_docs (user_id);

CREATE INDEX idx_worker_skills_sub_category ON worker_skills (sub_category);
CREATE INDEX idx_worker_skills_main_category ON worker_skills (main_category);
CREATE INDEX idx_worker_skills_worker_badge ON worker_skills (worker_id, badge_level);

-- ── 5. FOREIGN KEYS (added last, order-independent) ─────────

ALTER TABLE bookings ADD CONSTRAINT fk_bookings_client FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE bookings ADD CONSTRAINT fk_bookings_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE green_coin_transactions ADD CONSTRAINT fk_gct_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE green_coins ADD CONSTRAINT fk_gc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE greenloop_redemptions ADD CONSTRAINT fk_glred_reward FOREIGN KEY (reward_id) REFERENCES greenloop_rewards (id) ON DELETE CASCADE;
ALTER TABLE greenloop_redemptions ADD CONSTRAINT fk_glred_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE greenloop_reports ADD CONSTRAINT fk_glr_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE SET NULL;
ALTER TABLE greenloop_reports ADD CONSTRAINT fk_glr_client FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE greenloop_reports ADD CONSTRAINT fk_glr_item FOREIGN KEY (item_id) REFERENCES greenloop_accepted_items (id) ON DELETE SET NULL;

ALTER TABLE hr_permissions ADD CONSTRAINT fk_hr_permissions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE ip_whitelist ADD CONSTRAINT fk_ip_whitelist_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE job_candidates ADD CONSTRAINT fk_job_candidates_broadcast FOREIGN KEY (broadcast_id) REFERENCES job_broadcasts (id) ON DELETE CASCADE;

ALTER TABLE job_completion_proofs ADD CONSTRAINT fk_completion_proofs_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE;
ALTER TABLE job_completion_proofs ADD CONSTRAINT fk_completion_proofs_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE junkshop_sessions ADD CONSTRAINT fk_jsess_shop FOREIGN KEY (junkshop_id) REFERENCES junkshops (id) ON DELETE CASCADE;

ALTER TABLE messages ADD CONSTRAINT fk_messages_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- NOTE: no ON DELETE rule on purpose, matching the original — the source data
-- has a known pre-existing orphaned employee_id reference (see DEPLOY.md),
-- so this FK must be added AFTER the ETL data load, not before.
ALTER TABLE payroll_items ADD CONSTRAINT fk_pi_employee FOREIGN KEY (employee_id) REFERENCES employees (id);
ALTER TABLE payroll_items ADD CONSTRAINT fk_pi_run FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs (id) ON DELETE CASCADE;

ALTER TABLE portfolio_images ADD CONSTRAINT fk_portfolio_images_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE verification_nc_skills ADD CONSTRAINT fk_vncs_user FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE verification_nc_skills ADD CONSTRAINT fk_vncs_verification FOREIGN KEY (verification_id) REFERENCES verification (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE withdrawals ADD CONSTRAINT fk_withdrawals_approved_by FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE worker_skills ADD CONSTRAINT fk_ws_worker FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE;
